### ISSUE TITLE
Can not build under FreeBSD11

### ISSUE THREAD

**Issue by AlexanderThaller** [oxy-secure/oxy#110]
```
# rustc --version
rustc 1.28.0-nightly (01cc982e9 2018-06-24)
```

```
# uname -a
11.1-RELEASE-p10 FreeBSD 11.1-RELEASE-p10 #0: Tue May  8 05:21:56 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

```
# cargo install --git https://github.com/oxy-secure/oxy
    Updating git repository `https://github.com/oxy-secure/oxy`
  Installing oxy v2.0.2 (https://github.com/oxy-secure/oxy#6fd7e302)
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.3
   Compiling lazy_static v1.0.1
   Compiling memoffset v0.2.1
   Compiling scopeguard v0.3.3
   Compiling libc v0.2.42
   Compiling rayon-core v1.4.0
   Compiling num-traits v0.2.5
   Compiling num-integer v0.1.39
   Compiling build_const v0.2.1
   Compiling gcc v0.3.54
   Compiling num-iter v0.1.37
   Compiling unicode-xid v0.1.0
   Compiling rustc-serialize v0.3.24
   Compiling serde v1.0.66
   Compiling void v1.0.2
   Compiling regex v1.0.1
   Compiling ucd-util v0.1.1
   Compiling nix v0.11.0
   Compiling stable_deref_trait v1.1.0
   Compiling untrusted v0.5.1
   Compiling bitflags v1.0.3
   Compiling unicode-width v0.1.5
   Compiling utf8-ranges v1.0.0
   Compiling smallvec v0.6.2
   Compiling byteorder v1.2.3
   Compiling slab v0.4.0
   Compiling bitflags v0.4.0
   Compiling lazycell v0.6.0
   Compiling adler32 v1.0.3
   Compiling lazy_static v0.2.11
   Compiling quick-error v1.2.2
   Compiling strsim v0.7.0
   Compiling termcolor v0.3.6
   Compiling ansi_term v0.11.0
   Compiling encode_unicode v0.1.3
   Compiling vec_map v0.8.1
   Compiling shlex v0.1.1
   Compiling data-encoding v2.1.1
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.2
   Compiling arrayvec v0.4.7
   Compiling proc-macro2 v0.4.6
   Compiling crc v1.8.1
   Compiling num_cpus v1.8.0
   Compiling rand v0.4.2
   Compiling memchr v2.0.1
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling term_size v0.3.1
   Compiling atty v0.2.10
   Compiling termion v1.5.1
   Compiling unreachable v1.0.0
   Compiling regex-syntax v0.6.1
   Compiling owning_ref v0.3.3
   Compiling textwrap v0.9.0
   Compiling nix v0.5.1
   Compiling humantime v1.1.1
   Compiling crossbeam-epoch v0.3.1
   Compiling aho-corasick v0.6.4
   Compiling textwrap v0.10.0
   Compiling mio v0.6.14
   Compiling thread_local v0.3.5
   Compiling parking_lot_core v0.2.14
   Compiling lock_api v0.1.3
   Compiling quote v0.6.3
   Compiling clap v2.31.2
   Compiling crossbeam-deque v0.2.0
   Compiling rustyline v1.0.0
   Compiling parking_lot v0.6.2
   Compiling syn v0.14.2
   Compiling libflate v0.1.15
   Compiling num-complex v0.1.43
   Compiling num-traits v0.1.43
   Compiling num-bigint v0.1.44
   Compiling rmp v0.8.7
   Compiling rayon v0.8.2
   Compiling serde_cbor v0.8.2
   Compiling toml v0.4.6
   Compiling rmp-serde v0.13.7
   Compiling ring v0.12.1
   Compiling num-rational v0.1.42
   Compiling serde_derive v1.0.66
   Compiling num v0.1.42
   Compiling env_logger v0.5.10
   Compiling transportation v2.0.0
error[E0432]: unresolved import `nix::sys::signalfd`
 --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:4:30
  |
4 |         signal::Signal::{self, *}, signalfd::{siginfo, SfdFlags, SIGNALFD_SIGINFO_SIZE},
  |                                    ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0433]: failed to resolve. Could not find `signalfd` in `sys`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:23:22
   |
23 |         let fd = nix::sys::signalfd::signalfd(-1, &mask, flags).unwrap();
   |                            ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0433]: failed to resolve. Could not find `signalfd` in `sys`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:48:63
   |
48 |         let siginfo = unsafe { ::std::mem::transmute::<_, nix::sys::signalfd::siginfo>(buf) };
   |                                                                     ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0277]: the size for value values of type `[u8]` cannot be known at compilation time
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:44:7
   |
44 |         let mut buf = [0u8; SIGNALFD_SIGINFO_SIZE];
   |             ^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized>
   = note: all local variables must have a statically known size

error[E0277]: the size for value values of type `[u8]` cannot be known at compilation time
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:48:26
   |
48 |         let siginfo = unsafe { ::std::mem::transmute::<_, nix::sys::signalfd::siginfo>(buf) };
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized>
   = note: required by `std::intrinsics::transmute`

error: aborting due to 5 previous errors

Some errors occurred: E0277, E0432, E0433.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `transportation`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `oxy v2.0.2 (https://github.com/oxy-secure/oxy#6fd7e302)`, intermediate artifacts can be found at `/tmp/cargo-installaAX0Iw`

Caused by:
  build failed

```

**Comment by peacetara** [comment]
This is also true of macOS:
...
   Compiling transportation v2.0.0
error[E0432]: unresolved import `nix::sys::signalfd`
 --> /Users/zie/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:4:30
  |
4 |         signal::Signal::{self, *}, signalfd::{siginfo, SfdFlags, SIGNALFD_SIGINFO_SIZE},
  |                                    ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0433]: failed to resolve. Could not find `signalfd` in `sys`
  --> /Users/zie/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:23:22
   |
23 |         let fd = nix::sys::signalfd::signalfd(-1, &mask, flags).unwrap();
   |                            ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0433]: failed to resolve. Could not find `signalfd` in `sys`
  --> /Users/zie/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:48:63
   |
48 |         let siginfo = unsafe { ::std::mem::transmute::<_, nix::sys::signalfd::siginfo>(buf) };
   |                                                                     ^^^^^^^^ Could not find `signalfd` in `sys`

error[E0277]: the size for value values of type `[u8]` cannot be known at compilation time
  --> /Users/zie/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:44:7
   |
44 |         let mut buf = [0u8; SIGNALFD_SIGINFO_SIZE];
   |             ^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized>
   = note: all local variables must have a statically known size

error[E0277]: the size for value values of type `[u8]` cannot be known at compilation time
  --> /Users/zie/.cargo/registry/src/github.com-1ecc6299db9ec823/transportation-2.0.0/src/signals.rs:48:26
   |
48 |         let siginfo = unsafe { ::std::mem::transmute::<_, nix::sys::signalfd::siginfo>(buf) };
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |
   = help: the trait `std::marker::Sized` is not implemented for `[u8]`
   = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized>
   = note: required by `std::mem::transmute`

error: aborting due to 5 previous errors

Some errors occurred: E0277, E0432, E0433.
For more information about an error, try `rustc --explain E0277`.
error: Could not compile `transportation`.
warning: build failed, waiting for other jobs to finish...
error: build failed
$ rustc --version
rustc 1.28.0-nightly (01cc982e9 2018-06-24)
$ uname -a
Darwin host.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

which is 10.13.3 (17D102) (macOS High Sierra)

This is because the https://github.com/oxy-secure/transportation signal handling routines, since Rust apparently has a miserable signal handling story: https://github.com/rust-lang/rfcs/issues/1368

**Comment by myfreeweb** [comment]
Yeah, signals...

https://github.com/carllerche/mio/issues/16

There's [tokio-signal](https://github.com/alexcrichton/tokio-signal) for Tokio (also [chan-signal](https://github.com/BurntSushi/chan-signal) for chan, [signal-notify](https://github.com/agatan/signal-notify) for std mpsc channels) but nothing for just mio :(
And most of these libraries do not use signalfd or kqueue.

I'll look into making a PR to transportation with kqueue support..

**Comment by jennamagius** [comment]
I'm surprised if signals are the only thing blocking BSD support. I'd definitely love to support BSD properly, but I haven't been testing on BSD and less familiar with how to talk to a BSD kernel.

Pull requests are super welcome for BSD support issues, and I do plan on working on them myself eventually.

**Comment by myfreeweb** [comment]
> I'm surprised if signals are the only thing blocking BSD support.

Not the only thing, there's also a 7 character patch: https://github.com/oxy-secure/oxy/pull/114

And here you go: https://github.com/oxy-secure/transportation/pull/9 :)

**Comment by jennamagius** [comment]
Seems like @myfreeweb solved this. @AlexanderThaller , can you confirm if the dev branch builds for you now?

**Comment by peacetara** [comment]
on macOS still doesn't build:
```
cargo build
   Compiling oxy v3.0.0-dev1 (file:///Users/zie/src/oxy)
error[E0425]: cannot find function `getgrouplist` in module `nix::unistd`
  --> src/core/kex.rs:98:48
   |
98 |                 let grouplist = ::nix::unistd::getgrouplist(&cstr_setuser, gid);
   |                                                ^^^^^^^^^^^^ not found in `nix::unistd`

error[E0425]: cannot find function `setgroups` in module `nix::unistd`
   --> src/core/kex.rs:104:45
    |
104 |                 let result = ::nix::unistd::setgroups(&grouplist[..]);
    |                                             ^^^^^^^^^ not found in `nix::unistd`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `oxy`.

To learn more, run the command again with --verbose.
```

I don't have time to look into this more or try on other BSD's at the moment.

transportation crate builds now tho! Thanks @myfreeweb !!
by setting Cargo.toml's transportation dependency to:
```
transportation = { git = "https://github.com/oxy-secure/transportation.git", branch = "dev", features = ["protocol", "encrypt"] }
```

**Comment by jennamagius** [comment]
Yeah, getgrouplist should work on pure BSDs, just not on Mac: https://docs.rs/nix/0.11.0/nix/unistd/fn.getgrouplist.html

I don't have a mac at all, so I'm not going to be able to implement opendirectoryd integration. A cheesy temporary work around would be to just set the full supplementary groups list to the gid from getpwent and that's it.

**Comment by AlexanderThaller** [comment]
Now compiles fine with FreeBSD 11 when using the dev branch. Thank you!

**Comment by jennamagius** [comment]
Thank you!

**Comment by myfreeweb** [comment]
Update on signal solutions: new crate [signal-hook](https://docs.rs/signal-hook) looks pretty good. Has easy self-pipe support, and in the future they promise even better `mio` integration.

**Comment by jennamagius** [comment]
Good to know, thanks!
