### ISSUE TITLE
[BSD] Server listens on IPv6 only

### ISSUE THREAD

**Issue by myfreeweb** [oxy-secure/oxy#115]
Looks like oxy binds on  `[::]`, which is

- dual-stack by default (actually, depending on configuration, might not be!) on Linux
- v6-only by default on FreeBSD (interestingly, `mio` API offers `set_only_v6` that you can call... *after* the bind?!)
- v6-only *always* on OpenBSD and others

https://community.openvpn.net/openvpn/ticket/937?cversion=1&cnum_hist=5

I think two sockets should be used.

**Comment by jennamagius** [comment]
Yeah, mio::TcpListener::set_only_v6 is literally useless, because there's no way to do it before bind() and it doesn't work after the bind. It's inherited from the Rust stdlib: https://github.com/rust-lang/rust/issues/33052 ... it's a heck of a thing.

We'd basically just have to use the ::nix socket calls to make the socket and then ::mio::TcpListener::from_raw_socket.

I started out using two sockets, but gave up because set_only_v6 doesn't work.

I'll bust it out to two sockets eventually, or merge your PR. :+1:

**Comment by jennamagius** [comment]
I've pushed an implementation in dev: https://github.com/oxy-secure/oxy/commit/562e42780d526cc9bfa925153abc5bae8c044195

Instead of actually dropping down to ::nix, I think I can get away with just yoloing it and letting the IPv4 bind fail if the IPv6 bind is shadowing it? Please test it out and let me know what you think.

**Comment by myfreeweb** [comment]
Yeah, that works for me :) looks like a potential annoying warning on Linux though?

**Comment by jennamagius** [comment]
Oh yeah, those should all be debug!() for sure. I'll bump 'em down.

**Comment by jennamagius** [comment]
No, wait, are you talking about the "Failed to register" warn!()s? Those should only fire in the weird case that bind() actually succeeds but then epoll_ctl() is what fails. If it fails on bind() (where it should) it just moves along silently.

**Comment by myfreeweb** [comment]
Oh, right, I can't read apparently lol
