### ISSUE TITLE
knock replay

### ISSUE THREAD

**Issue by mikedilger** [oxy-secure/oxy#123]
What prevents an exact knock replay from a different IP address within 60 seconds or so?  A timestamp is not quite a nonce.

Why not
1) include a random component in the nonce, keeping the time component,
2) On the server store nonces used so far, but expire them after 120 seconds or so (don't store them forever) -- I suppose this may lead to a DoS vector if they come fast enough

**Comment by dcarosone** [comment]
The server could also only accept knocks with timestamps strictly greater than the last knock received (globally, or per-ip, with different tradeoffs).

I didn't look, but is the timestamp sent with the knock already rounded, or sent at high precision?  Or is there not a timestamp included in the body at all?

**Comment by jennamagius** [comment]
There's no timestamp in the body at all, the body is 100 bytes derived by hashing the knock key with the rounded timestamp.

I see the appeal of putting a nonce in the knock, and I think it could be done without increasing the external surface area too much, but I'm not sure exactly what the threat model is.

I guess it's like: an attacker is mitm, and that's how they gain possession of a knock value in the first place. And they have an exploit that they can trigger by opening multiple TCP connections with different sources?

I'd merge a PR.

**Comment by dcarosone** [comment]
`protocol.txt` says that the payload is the hash, without the timestamp data itself, so something has to be added and in that case it might as well be a proper nonce

**Comment by mikedilger** [comment]
I'm still just getting my head around it, and I'll be digging into the code more before any PR.
It seems changes would be mostly isolated to `keys.rs` in `make_knock()` and `verify_knock()`.

The problem is that the nonce inside of the hash means the server can't just try 3 knock values and compare.  So the design change would be substantial and I don't yet know if its even worth it.

@dcarosone I think storing (last timestamp + ip address) doesn't seem sufficient because you can have two machines with different clock skews behind a NAT. Someone with their clock a bit behind might be denied access. Not a security issue but could be an annoying edge case.

**Comment by dcarosone** [comment]
the server could also just keep a list of the actual knock payloads already accepted (with some time+space bounds to guard against DoS) with no need to carry additional payload. That would limit legitimate users to one connection per ~60s, since those are effectively going to regenerate the same knock too.

For threat model, it's (at least) that whatever value the knock mechanism offers is devalued if they can be replayed, and perhaps to the point where the value is less than the complexity added (firewall config etc).  Anything worse assumes additional vulns, as you note.

My impression is that the primary value of the knock is server discoverability. If someone is mitm they can observe knocks and subsequent oxy traffic enough to discover the server regardless. So it seems unclear.

@mikedilger good point about the NAT; I was declining to suggest using the client's IP in the hash because of NAT, but that too.

**Comment by mikedilger** [comment]
As for threat model, I was just presuming that the timestamp in the knock was there for a "nonce like" reason.

**Comment by mikedilger** [comment]
A first pass is here: https://github.com/mikedilger/oxy/tree/knock_salt

Not a PR yet, I'll look at it again tomorrow.

I didn't understand the purpose of KNOCK_VALUES in keys.rs and removed it. Server has it's own 50 second memory.

**Comment by jennamagius** [comment]
Your implementation looks good to me. I think I'm pretty attached to caching values on the server side, but if you put a cache back in I'd merge it.

**Comment by jennamagius** [comment]
Oh yeah, I can see how that's a problem. Uh... I'm not sure immediately. There might not be a great way to dodge both the replay attack and the resource exhaustion attack at the same time. I think between the two I'm more married to minimizing the resource exhaustion attack, because it doesn't even require MITM to perform.

I'll stew on it, hopefully there's a way to get both.

**Comment by jennamagius** [comment]
Cheating the nock gives you access to the kex codepaths. Those themselves are designed to be low surface area. Still more than I'd like, but still fully in the "malfeasance expected" zone.

But if you're MITM you don't even need to cheat the knock to get access to the kex codepaths. You just let the knock happen and then go in the front door using the same source IP.

**Comment by mikedilger** [comment]
> But if you're MITM you don't even need to cheat the knock to get access to the kex codepaths. You just let the knock happen and then go in the front door using the same source IP.
True. I'll think about this more tomorrow, getting late here. I was never sure if this was worth it, and if I don't wake up with an easy answer then its probably best to just leave things as they are.  BTW I wouldn't have raised an issue if I didn't think oxy was pretty cool, so thanks for oxy.

**Comment by jennamagius** [comment]
Thank you!

**Comment by dcarosone** [comment]
> But if you're MITM you don't even need to cheat the knock to get access to the kex codepaths. You just let the knock happen and then go in the front door using the same source IP.

Yeah, I was going to make the same point earlier.  The only way to avoid this is to include a nonce from the knock in the kex phase somehow, and it probably also becomes a more elaborate multi-packet port-knocking sequence. Really at that point it stops being a knock and becomes extra kex. Boundaries blur and it seems not worth it.

So if the end result of this is just that there's greater clarity (expressed in the docs) over the purpose and role (inclusions *and* exclusions) of the knock, that's a win. People who want to avoid the knock phase entirely (because of firewall rules) will be able to make the informed decision, but an inevitable consequence will be that some of them will want an always-listen-tcp knock-free mode.

**Comment by mikedilger** [comment]
KNOCK_VALUES peer column, on the server, appears to always be None. I was going to suggest that IP spoofing would allow a client to continue to knock and cause the same DoS, but not if the peer is always set to None. So I don't have any good ideas, and I suppose leaving it as is makes the most sense for now.
